all:
  admin:
    # set to false to prevent generation of global flashes and addition of flashes in modules
    include_flashes: true
    
    # set to false to prevent addition of view.yml in generated module's config
    stylesheets:    [/sfHadoriThemePlugin/css/hadori.css]